# Generated by Django 5.1.14 on 2026-01-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=200)),
                (
                    "bio_short",
                    models.TextField(help_text="The short bio under the name"),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name_plural": "Profile",
            },
        ),
    ]
