# Generated by Django 5.1.14 on 2026-01-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Education", "Education"),
                            ("Research", "Research"),
                            ("Opinion", "Opinion"),
                        ],
                        default="Education",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("date_published", models.DateField(auto_now_add=True)),
                (
                    "summary",
                    models.TextField(help_text="Short description for the card"),
                ),
            ],
            options={
                "ordering": ["-date_published"],
            },
        ),
    ]
