# Generated by Django 5.1.15 on 2026-02-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL gambar untuk blog post (gunakan Google Photos, Imgur, dll)",
                max_length=500,
                null=True,
            ),
        ),
    ]
