# Generated by Django 5.1.15 on 2026-02-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image_url",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Gambar untuk blog post",
                null=True,
                upload_to="blog_images/",
            ),
        ),
    ]
